220607：コントローラを追加
hikaway/laravel-study pull request #2
Opened 2022-06-07 13:47 UTC by hikaway

2022-06-07 14:12 UTC, Mitsuru53 requested changes

2022-06-07 14:12 UTC, Mitsuru53 commented on routes/web.php
> +use App\Http\Controllers\twitController;
use系の宣言は3行目の次に記述してください！
同様の処理をまとめておいたほうが可読性が高いですね

2022-06-07 14:12 UTC, Mitsuru53 commented on routes/web.php
> +use App\Http\Controllers\twitController;
クラス(twitController)名の先頭文字は大文字するのが慣習的に多いですね
また複数形にすることが多いです
ので、twitControllerではなくTweetsControllerの方が望ましいかと存じます！

2022-06-07 14:12 UTC, Mitsuru53 commented on routes/web.php
> +use App\Http\Controllers\twitController;
https://github.com/hikaway/laravel-study/tree/issue1/app/Http/Controllers
コントローラーが作成されていないようです！

artisanコマンドでTweetsControllerを作成してください！

2022-06-07 14:12 UTC, Mitsuru53 commented on routes/web.php
> +    'posts' => twitController::class,
postsではなくtweetsの方がいいかなと思いました。
TweetsControllerコントローラーはつぶやき(tweet)に関するものなので、urlも併せてtweetsにしておいた方が整合性があると思われます！

2022-06-08 02:58 UTC, hikaway reviewed
220608：07レビュー修正

2022-06-08 10:59 UTC, Mitsuru53 approved these changes

2022-06-16 01:14 UTC, merged